version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
parameters:
  root-dir:
    type: string
    default: "labmotus-project"
  types-dir:
    type: string
    default: "labmotus-project/common/types"
  ui-dir:
    type: string
    default: "labmotus-project/common"
  cloud-dir:
    type: string
    default: "labmotus-project/cloud"
  lambda-dir:
    type: string
    default: "labmotus-project/lambda"
  clinician-dir:
    type: string
    default: "labmotus-project/clinician-app"
  patient-dir:
    type: string
    default: "labmotus-project/patient-app"
jobs:
  run-tests:
    docker:
      - image: cimg/node:15.10.0
    steps:
      - checkout
      - run:
          command: |
            npm i --prefix << pipeline.parameters.root-dir >>
            npm i --prefix << pipeline.parameters.types-dir >>
            npm i --prefix << pipeline.parameters.cloud-dir >>
            npm run test --prefix << pipeline.parameters.cloud-dir >>
            npm i --prefix << pipeline.parameters.lambda-dir >>
            npm run test --prefix << pipeline.parameters.lambda-dir >>
            npm i --prefix << pipeline.parameters.patient-dir >>
            ln -s << pipeline.parameters.patient-dir >>/node_modules << pipeline.parameters.ui-dir >>/node_modules
            npm run test --prefix << pipeline.parameters.patient-dir >>
            npm i --prefix << pipeline.parameters.clinician-dir >>
            rm << pipeline.parameters.ui-dir >>/node_modules
            ln -s << pipeline.parameters.clinician-dir >>/node_modules << pipeline.parameters.ui-dir >>/node_modules
            npm run test --prefix << pipeline.parameters.clinician-dir >>
  deploy-cloud:
    docker:
      - image: cimg/python:3.9-node
    steps:
      - checkout
      - run:
          name: Build and deploy API
          command: |
            pip install awsebcli
            npm i --prefix << pipeline.parameters.root-dir >>
            npm i --prefix << pipeline.parameters.types-dir >>
            npm i -D --prefix << pipeline.parameters.cloud-dir >>
            echo $CLOUD_CONFIG > << pipeline.parameters.cloud-dir >>/config.json
            echo $FIREBASE_SERVICE_KEY > << pipeline.parameters.cloud-dir >>/firebase-service-key.json
            echo $WRNCH_API_KEY > << pipeline.parameters.cloud-dir >>/WRNCH_API_KEY
            mkdir .elasticbeanstalk
            echo $EB_CONFIG > .elasticbeanstalk/config.yml
            cat << pipeline.parameters.cloud-dir >>/config.json
            npm run build --prefix << pipeline.parameters.cloud-dir >>
            git config user.email "circleci@circleci.com"
            git config user.name "CircleCI"
            git add -f *
            git commit -m "Build API"
            eb deploy $CLOUD_ENV
  deploy-lambda:
    docker:
      - image: cimg/python:3.9-node
    steps:
      - checkout
      - run:
          name: Build and deploy lambda function
          command: |
            pip install awscli
            npm i -D --prefix << pipeline.parameters.lambda-dir >>
            echo $LAMBDA_CONFIG > << pipeline.parameters.lambda-dir >>/config.json
            echo $WRNCH_API_KEY > << pipeline.parameters.lambda-dir >>/WRNCH_API_KEY
            sudo apt update
            sudo apt install p7zip-full
            7z a /tmp/lambda.zip ./<< pipeline.parameters.lambda-dir >>/*
      - store_artifacts:
          path: /tmp/lambda.zip
  deploy-clinician:
    docker:
      - image: cimg/node:15.10.0
    steps:
      - checkout
      - run:
          name: Build project
          command: |
            npm i --prefix << pipeline.parameters.root-dir >>
            npm i --prefix << pipeline.parameters.types-dir >>
            npm i --prefix << pipeline.parameters.patient-dir >>
            npm i -D --prefix << pipeline.parameters.clinician-dir >>
            echo $CLINICIAN_CONFIG > << pipeline.parameters.clinician-dir >>/config.json
            npm run build --prefix << pipeline.parameters.clinician-dir >>
      - aws-s3/sync:
          from: << pipeline.parameters.clinician-dir >>/build
          to: 's3://$CLINICIAN_BUCKET'
          arguments: '--acl public-read'
  deploy-patient:
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout
      - run:
          name: Build project
          command: |
            npm i --prefix << pipeline.parameters.root-dir >>
            npm i --prefix << pipeline.parameters.types-dir >>
            npm i -D --prefix << pipeline.parameters.patient-dir >>
            echo $PATIENT_CONFIG > << pipeline.parameters.patient-dir >>/config.json
            npm i @ionic/cli
            npm i @capacitor/cli
            cd << pipeline.parameters.patient-dir >>
            npx ionic build
            npx cap sync
            cd android
            chmod +x ./gradlew
            ./gradlew build
            cd ~/project
      - aws-s3/copy:
          from: << pipeline.parameters.patient-dir >>/android/app/build/outputs/apk/debug/app-debug.apk
          to: 's3://labmotus-misc/$PATIENT_FILENAME'
          arguments: '--acl public-read'
workflows:
  test-and-deploy-dev:
    jobs:
      - deploy-cloud:
          filters:
            branches:
              only: develop
          context:
            - labmotus-aws
            - labmotus-firebase
            - labmotus-wrnch
            - labmotus-dev
      - deploy-lambda:
          filters:
            branches:
              only: develop
          context:
            - labmotus-aws
            - labmotus-wrnch
            - labmotus-dev
      - deploy-clinician:
          filters:
            branches:
              only: develop
          context:
            - labmotus-aws
            - labmotus-dev
      - deploy-patient:
          filters:
            branches:
              only: develop
          context:
            - labmotus-aws
            - labmotus-dev
  test-and-deploy-production:
    jobs:
      - deploy-cloud:
          filters:
            branches:
              only: main
          context:
            - labmotus-aws
            - labmotus-firebase
            - labmotus-wrnch
            - labmotus-production
      - deploy-lambda:
          filters:
            branches:
              only: main
          context:
            - labmotus-aws
            - labmotus-wrnch
            - labmotus-production
      - deploy-clinician:
          filters:
            branches:
              only: main
          context:
            - labmotus-aws
            - labmotus-production
      - deploy-patient:
          filters:
            branches:
              only: main
          context:
            - labmotus-aws
            - labmotus-production
