version: 2.1
parameters:
  root-dir:
    type: string
    default: "labmotus-project"
  types-dir:
    type: string
    default: "labmotus-project/common/types"
  ui-dir:
    type: string
    default: "labmotus-project/common"
  cloud-dir:
    type: string
    default: "labmotus-project/cloud"
  clinician-dir:
    type: string
    default: "labmotus-project/clinician-app"
  patient-dir:
    type: string
    default: "labmotus-project/patient-app"
jobs:
  run-tests:
    docker:
      - image: cimg/node:15.10.0
    steps:
      - checkout
      - run:
          command: |
            npm i --prefix << pipeline.parameters.root-dir >>
            npm i --prefix << pipeline.parameters.types-dir >>
            npm i --prefix << pipeline.parameters.cloud-dir >>
            npm run test --prefix << pipeline.parameters.cloud-dir >>
            npm i --prefix << pipeline.parameters.ui-dir >>
            npm i --prefix << pipeline.parameters.patient-dir >>
            npm run test --prefix << pipeline.parameters.patient-dir >>
            npm i --prefix << pipeline.parameters.clinician-dir >>
            npm run test --prefix << pipeline.parameters.clinician-dir >>
  deploy-cloud:
    docker:
      - image: cimg/python:3.9-node
    steps:
      - checkout
      - run:
          name: Build and deploy API
          command: |
            pip install awsebcli
            npm i --prefix << pipeline.parameters.root-dir >>
            npm i --prefix << pipeline.parameters.types-dir >>
            npm i -D --prefix << pipeline.parameters.cloud-dir >>
            echo $FIREBASE_SERVICE_KEY > << pipeline.parameters.cloud-dir >>/firebase-service-key.json
            npm run build --prefix << pipeline.parameters.cloud-dir >>
            git config user.email "circleci@circleci.com"
            git config user.name "CircleCI"
            git add -f *
            git commit -m "Build API"
            eb deploy labmotus-api
workflows:
  test-and-deploy:
    jobs:
      - deploy-cloud:
          filters:
            branches:
              only: main
          context:
            - labmotus-aws
            - labmotus-firebase
