version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
parameters:
  root-dir:
    type: string
    default: "labmotus-project"
  types-dir:
    type: string
    default: "labmotus-project/common/types"
  ui-dir:
    type: string
    default: "labmotus-project/common"
  cloud-dir:
    type: string
    default: "labmotus-project/cloud"
  clinician-dir:
    type: string
    default: "labmotus-project/clinician-app"
  patient-dir:
    type: string
    default: "labmotus-project/patient-app"
jobs:
  run-tests:
    docker:
      - image: cimg/node:15.10.0
    steps:
      - checkout
      - run:
          command: |
            npm i --prefix << pipeline.parameters.root-dir >>
            npm i --prefix << pipeline.parameters.types-dir >>
            npm i --prefix << pipeline.parameters.cloud-dir >>
            npm run test --prefix << pipeline.parameters.cloud-dir >>
            npm i --prefix << pipeline.parameters.patient-dir >>
            ln -s << pipeline.parameters.patient-dir >>/node_modules << pipeline.parameters.ui-dir >>/node_modules
            npm run test --prefix << pipeline.parameters.patient-dir >>
            npm i --prefix << pipeline.parameters.clinician-dir >>
            rm << pipeline.parameters.ui-dir >>/node_modules
            ln -s << pipeline.parameters.clinician-dir >>/node_modules << pipeline.parameters.ui-dir >>/node_modules
            npm run test --prefix << pipeline.parameters.clinician-dir >>
  deploy-cloud:
    docker:
      - image: cimg/python:3.9-node
    steps:
      - checkout
      - run:
          name: Build and deploy API
          command: |
            pip install awsebcli
            npm i --prefix << pipeline.parameters.root-dir >>
            npm i --prefix << pipeline.parameters.types-dir >>
            npm i -D --prefix << pipeline.parameters.cloud-dir >>
            echo $FIREBASE_SERVICE_KEY > << pipeline.parameters.cloud-dir >>/firebase-service-key.json
            npm run build --prefix << pipeline.parameters.cloud-dir >>
            git config user.email "circleci@circleci.com"
            git config user.name "CircleCI"
            git add -f *
            git commit -m "Build API"
            eb deploy labmotus-api
  deploy-clinician:
    docker:
      - image: cimg/node:15.10.0
    steps:
      - checkout
      - run:
          name: Build project
          command: |
            npm i --prefix << pipeline.parameters.root-dir >>
            npm i --prefix << pipeline.parameters.types-dir >>
            npm i -D --prefix << pipeline.parameters.clinician-dir >>
            ln -s << pipeline.parameters.clinician-dir >>/node_modules << pipeline.parameters.ui-dir >>/node_modules
            npm run build --prefix << pipeline.parameters.clinician-dir >>
      - aws-s3/sync:
          from: << pipeline.parameters.clinician-dir >>/build
          to: 's3://labmotus-clinician'
          arguments: '--acl public-read'
  deploy-patient:
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout
      - run:
          name: Build project
          command: |
            npm i --prefix << pipeline.parameters.root-dir >>
            npm i --prefix << pipeline.parameters.types-dir >>
            npm i -D --prefix << pipeline.parameters.patient-dir >>
            ln -s << pipeline.parameters.patient-dir >>/node_modules << pipeline.parameters.ui-dir >>/node_modules
            npm i @ionic/cli
            npm i @capacitor/cli
            cd << pipeline.parameters.patient-dir >>
            npx cap update android
            npx ionic build
            npx cap sync
            cd android
            ./gradlew build
workflows:
  test-and-deploy:
    jobs:
      - deploy-cloud:
          filters:
            branches:
              only: main
          context:
            - labmotus-aws
            - labmotus-firebase
      - deploy-clinician:
          filters:
            branches:
              only: main
          context:
            - labmotus-aws
      - deploy-patient