version: 2.1
parameters:
  root-dir:
    type: string
    default: "labmotus-project"
  types-dir:
    type: string
    default: "labmotus-project/common/types"
  ui-dir:
    type: string
    default: "labmotus-project/common"
  cloud-dir:
    type: string
    default: "labmotus-project/cloud"
  clinician-dir:
    type: string
    default: "labmotus-project/clinician-app"
  patient-dir:
    type: string
    default: "labmotus-project/patient-app"
jobs:
  run-tests:
    docker:
      - image: cimg/node:15.10.0
    steps:
      - checkout
      - run:
          command: |
            npm i --prefix << pipeline.parameters.root-dir >>
            npm i --prefix << pipeline.parameters.types-dir >>
            npm i --prefix << pipeline.parameters.cloud-dir >>
            npm run test --prefix << pipeline.parameters.cloud-dir >>
            npm i --prefix << pipeline.parameters.ui-dir >>
            npm i --prefix << pipeline.parameters.patient-dir >>
            npm run test --prefix << pipeline.parameters.patient-dir >>
            npm i --prefix << pipeline.parameters.clinician-dir >>
            npm run test --prefix << pipeline.parameters.clinician-dir >>
  deploy-cloud:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          command: |
            pip install awsebcli
            echo $FIREBASE_SERVICE_KEY > labmotus-project/cloud/firebase-service-key.json
            git config user.email "circleci@circleci.com"
            git config user.name "CircleCI"
            git commit -a
            eb deploy labmotus-api
workflows:
  test-and-deploy:
    jobs:
      - run-tests
      - deploy-cloud:
          context:
            - labmotus-aws
            - labmotus-firebase
